### ISSUE TITLE
Empty trains synchronization

### ISSUE THREAD

**Issue by slanguloc** [mariomulansky/PySpike#29]
Hi Mario,

I am using a set of spike trains that contains zero spikes in a pre-stimulus condition. The synchronization between empty spike trains seems to get a value of 1.0. Is there a way to modify this condition and have a an output of 0.0?

Thanks,

Sergio

**Comment by mariomulansky** [comment]
We decided to define two empty spike trains as "fully synchronous" because the absence of spikes in both spike trains can be viewed as them being similar. But I agree this is somewhat arbitrary and I can see how a different definition makes sense as well. Unfortunately it is not that simple to change this behavior inside of PySpike. But I think it should be easy to check this condition (both spike trains empty) yourself before calling PySpikes functions?

**Comment by thomaskreuz** [comment]
PySpike should provide a defined synchronisation value for two empty spike trains. To us 1 seems most reasonable, since two empty spike trains are also identical. But as mentioned above if this is not satisfactory it should be easy to change this in the program that calls PySpike.

For a more detailed discussion of such special cases for all three measures ISI-distance, SPIKE-distance, and SPIKE-Synchronisation please refer to Appendix A of this article:

[Measures of spike train synchrony for data with multiple time-scales](https://drive.google.com/file/d/1xOepp9WN0luODH9qF6i5vVRimqC9WweA/view)
Satuvuori E, Mulansky M, Bozanic N, Malvestio I, Zeldenrust F, Lenk K, Kreuz T
[[arXiv](https://arxiv.org/pdf/1702.05394.pdf)] and JNeurosci Methods 287, 25 (2017) [[PDF](https://www.sciencedirect.com/science/article/pii/S0165027017301619)]
