### ISSUE TITLE
update docs to describe Figure scale

### ISSUE THREAD

**Issue by dohalloran** [mariomulansky/PySpike#43]
no documentation describing how to make scale for plots similar to Fig4 in the PySpike paper in SoftwareX

**Comment by thomaskreuz** [comment]
The PySpike documentation provides an introduction to how to calculate the underlying measures and how to show the results in basic plots using the Python library "Matplotlib". These plots can then easily be extended using further Matplotlib commands. Since this is not the core part of what PySpike does for further details we refer to the vast literature on Matplotlib.

For example, more information on basic plotting (such as axis scales) can be found [here](https://matplotlib.org/stable/tutorials/introductory/quick_start.html#sphx-glr-tutorials-introductory-quick-start-py).
